#!/bin/bash

set -eu

IMAGE="${IMAGE:-ghcr.io/manics/jupyter-desktop-antigravity:latest}"
RUNTIME_DIR="$HOME/containers/antigravity"
PORT=5901
RESOURCES=(--cpus=2 --memory=4g --shm-size=2g)
# Empty: disable authentication
PASSWORD="${PASSWORD:-}"
NAME=antigravity

ENGINE_ARGS=()
CMD_ARGS=()
while [ $# -gt 0 ]; do
  if [ "$1" = "--" ]; then
    shift
    CMD_ARGS=("$@")
    break
  fi
  ENGINE_ARGS+=("$1")
  shift
done

if command -v podman &> /dev/null; then
  ENGINE=podman
else
  ENGINE=docker
fi

if "$ENGINE" container exists $NAME; then
  "$ENGINE" start -ai $NAME
else
  "$ENGINE" run -it \
    --name=$NAME \
    --rm \
    -e PASSWORD="$PASSWORD" \
    -p 127.0.0.1:$PORT:5901 \
    "${RESOURCES[@]}" \
    -v "$RUNTIME_DIR:/home/jovyan:z" \
    --tmpfs /tmp \
    --read-only \
    "${ENGINE_ARGS[@]}" \
    $IMAGE \
    start-tigervnc.sh \
    "${CMD_ARGS[@]}"
fi
